### ISSUE TITLE
multiple instances of zpd

### ISSUE THREAD

**Issue by greglbd** [huei90/snap.svg.zpd#28]
I'd like to have multiple instances for zpd in the same page but when i do this they both silently fail.  no errors...

Has anyone tried this before?

**Comment by tikiatua** [comment]
Hi @greglbd,

this is due to the current implementation of the plugin. The beta-branch contains a completely reworked plugin-structure, that also supports responsive svgs (with viewBox and viewport set). 

The code is still under heavy development and the api will likely change. However, I have been using using the current beta-version in production for several weeks now and it works perfectly fine for me. You might though have to edit some plugin code to make it work for your project.

I hope to be able to do some further work on the beta-branch and incorporate support for touch devices in the coming weeks.

**Comment by tikiatua** [comment]
See #47
